services:
  - type: web
    name: leads-system
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: WHATSAPP_TO
        value: "+85221101144"
    plan: free
    autoDeploy: true